### ISSUE TITLE
Usable on Rasp Pi?

### ISSUE THREAD

**Issue by cambiata** [benyanke/GrandOrguePi#1]
Hi Ben!

Just found your repo! 
What's your experience with Grand Orgue on Rasp Pi?
Is it usable?

Best!

Jonas

**Comment by benyanke** [comment]
For practice purposes, with a smaller sample set, the RaspPi3 is more than sufficient. Only tested this script on the Pi2, didn't actually play much.

You're not going to be loading 80 rank organs, but a simple 5-10 rank will load and play just fine.

**Comment by cambiata** [comment]
Very interesting!
Thank you! Looking forward to try it!

Jonas
